In [5]:
import pandas as pd
import os

In [6]:
project_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
data_dir = os.path.join(project_root, "data") 

hydro_df = pd.read_csv(os.path.join(data_dir, "jrc-hydro-power-plant-database.csv"))

# Display basic information
print(hydro_df.info())  # Check column names and data types
print(hydro_df.head())  # Preview first few row

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4264 entries, 0 to 4263
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         4264 non-null   object
 1   name                       4264 non-null   object
 2   installed_capacity_MW      4264 non-null   float64
 3   pumping_MW                 187 non-null    float64
 4   type                       4264 non-null   object
 5   country_code               4264 non-null   object
 6   lat                        4264 non-null   float64
 7   lon                        4264 non-null   float64
 8   dam_height_m               1947 non-null   float64
 9   volume_Mm3                 1259 non-null   float64
 10  storage_capacity_MWh       871 non-null    float64
 11  avg_annual_generation_GWh  1554 non-null   float64
 12  pypsa_id                   1472 non-null   float64
 13  GEO                        513 non-null    float64
 14  WRI                        37 non-null     object
dtypes: float64(10), object(5)
memory usage: 499.8+ KB
None
      id                                               name  \
0     H1  Grande Dixence - Cleuson-Dixence (chandolin-fi...
1    H10                                  Chiotas entracque
2   H100        S.massenza - Vezzano molveno UP_S MASS CL_1
3  H1000  Lugo di nazza Lugo Di Nazza Hydroelectric Powe...
4  H1001                                          Pracomune

   installed_capacity_MW  pumping_MW  type country_code        lat        lon  \
0            2069.000000         NaN  HDAM           CH  46.073100   7.403400
1            1064.000000      1184.0  HPHS           IT  44.177576   7.416505
2             377.000000        55.0  HPHS           IT  46.067653  10.983605
3              38.503185         NaN  HDAM           FR  42.091000   9.316000
4              42.000000        35.6  HPHS           IT  46.547808  11.007077

   dam_height_m  volume_Mm3  storage_capacity_MWh  avg_annual_generation_GWh  \
0        1748.0      400.00             1764300.0                     1400.0
1         130.0       30.18               16860.0                        NaN
2         580.9       32.70               44800.0                        NaN
3           NaN         NaN                   NaN                        NaN
4         377.0         NaN                   NaN                        NaN

   pypsa_id      GEO         WRI
0       NaN  45218.0  WRI1004074
1     831.0  45432.0  WRI1002882
2     251.0      NaN         NaN
3    3125.0  39764.0         NaN
4    3234.0      NaN         NaN

In [10]:
# Print unique values in the "Country Code" column to verify its contents
print("Unique country codes in hydro_df:")
print(hydro_df["country_code"].unique())

Unique country codes in hydro_df:
['CH' 'IT' 'FR' 'SK' 'DE' 'ES' 'AT' 'SI' 'SE' 'UK' 'FI' 'EL' 'RO' 'AL'
 'BG' 'HR' 'PT' 'MK' 'RS' 'CZ' 'ME' 'BA' 'HU' 'IE' 'PL' 'BE' 'LV' 'LT'
 'XK' 'NO']

In [11]:
# Filter for Greece only
hydro_gr_df = hydro_df[hydro_df["country_code"] == "EL"].copy()

In [13]:
# Count the number of hydro-power plants in Greece
num_greek_plants = hydro_gr_df.shape[0]

print(f"✅ Number of hydro-power plants in Greece: {num_greek_plants}")

✅ Number of hydro-power plants in Greece: 21

In [14]:
plant_catalog_df = pd.read_csv(os.path.join(data_dir, "plant_catalog.csv"))

In [15]:
plant_catalog_df

            eic_code           plant_name                         psr_type
0   29WYISSFIKIAS--8               SFIKIA             Hydro Pumped Storage
1   29WTHESAVROS3--V  THESAVROS III_HYDRO             Hydro Pumped Storage
2   29WTHESAVROS2--Z   THESAVROS II_HYDRO             Hydro Pumped Storage
3   29WTHESAVROS1--2    THESAVROS I_HYDRO             Hydro Pumped Storage
4   29WYISAGRA-----I                AGRAS  Hydro Run-of-river and poundage
5   29WYISEDESSAIOUM            EDESSAIOS  Hydro Run-of-river and poundage
6   29WYISPIGONAOOUX                 AOOS            Hydro Water Reservoir
7   29WYISASOMATON-H              ASOMATA            Hydro Water Reservoir
8   29WILARIONAS---X            ILARIONAS            Hydro Water Reservoir
9   29WYISKASTRAKI-M             KASTRAKI            Hydro Water Reservoir
10  29WYISKREMASTONE             KREMASTA            Hydro Water Reservoir
11  29WYISLADONAS--V              LADONAS            Hydro Water Reservoir
12  29WYISNPLASTIRAF            PLASTIRAS            Hydro Water Reservoir
13  29WYISPLATANOVRH         PLATANOVRYSI            Hydro Water Reservoir
14  29WYISPOLYFYTO-O             POLYFYTO            Hydro Water Reservoir
15  29WYISPOURNARI-P           POURNARI I            Hydro Water Reservoir
16  29WYISPOURNARIIO            POURNARI2            Hydro Water Reservoir
17  29WYISSTRATOU-IV             STRATOS1            Hydro Water Reservoir

In [16]:
hydro_gr_df

,id,name,installed_capacity_MW,pumping_MW,type,country_code,lat,lon,dam_height_m,volume_Mm3,storage_capacity_MWh,avg_annual_generation_GWh,pypsa_id,GEO,WRI
21,H102,Polyfyto POLYFYTO - Polyfyto Hydroelectric Po...,375.0,NaN,HDAM,EL,40.330500,22.125300,105.0,1220.0,342000.0,584.0,2966.0,42797.0,NaN
215,H124,Pournari,334.0,NaN,HDAM,EL,39.184500,21.025500,87.0,730.0,50000.0,540.0,2967.0,42799.0,NaN
326,H136,Kastraki KASTRAKI - Kastraki Hydroelectric Pow...,320.0,NaN,HDAM,EL,38.741500,21.364200,95.7,950.0,25000.0,930.0,2939.0,42793.0,NaN
354,H139,Sfikia SFIKIA - Sfikia Hydroelectric Power Pla...,315.0,315.0,HPHS,EL,40.385657,22.211378,81.0,18.0,1320.0,NaN,2893.0,42802.0,NaN
392,H1429,EDESSAIOS,19.0,NaN,HROR,EL,40.804001,22.056684,NaN,NaN,NaN,NaN,NaN,NaN,NaN
635,H1713,MAKROHORI-I,11.0,NaN,HROR,EL,40.541462,22.262665,NaN,NaN,NaN,NaN,NaN,NaN,NaN
650,H1731,LOUROS,10.3,NaN,HROR,EL,39.251598,20.864800,NaN,NaN,NaN,NaN,NaN,NaN,NaN
756,H1856,GHIONA,8.0,NaN,HROR,EL,38.546509,22.354761,NaN,NaN,NaN,NaN,NaN,NaN,NaN
774,H1880,STRATOS-II - Stratos Hydroelectric Power Plant...,7.0,NaN,HROR,EL,38.675804,21.325890,26.0,80.0,NaN,NaN,NaN,NaN,NaN
817,H195,P_AOOU - Aoos (Piges Aoos) Hydroelectric Power...,230.0,NaN,HDAM,EL,39.836109,21.066389,78.0,180.0,242000.0,NaN,NaN,42792.0,NaN
861,H2024,GLAFKOS-II,4.8,NaN,HROR,EL,38.190485,21.800672,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1790,H300,Mesochora Hydroelectric Power Plant Greece - M...,162.0,NaN,HDAM,EL,39.464400,21.304200,150.0,NaN,NaN,NaN,NaN,42791.0,NaN
2028,H322,Ilarionas ILARIONAS - Ilarionas Hydroelectric ...,154.0,NaN,HDAM,EL,40.096600,21.803900,130.0,520.0,72000.0,413.0,3000.0,42790.0,NaN
2121,H331,Stratos,150.0,NaN,HDAM,EL,38.676000,21.323300,26.0,80.0,1000.0,NaN,2979.0,42800.0,NaN
2541,H391,Plastiras PLASTIRAS - Plastira Hydroelectric P...,130.0,NaN,HDAM,EL,39.236100,21.746200,83.0,400.0,392000.0,NaN,2962.0,42795.0,NaN
2587,H441,Platanovrysi PLATANOVRYSI - Platanovrisi Hydro...,116.0,NaN,HDAM,EL,41.335500,24.462100,95.0,57.0,11000.0,NaN,2963.0,42796.0,NaN
2612,H476,Asomata ASOMATA - Asomata Hydroelectric Power ...,108.0,NaN,HDAM,EL,40.474400,22.243900,52.0,3.0,1000.0,NaN,2916.0,42789.0,NaN
2774,H664,Ladonas LADONAS,70.0,NaN,HDAM,EL,37.750000,21.883333,NaN,NaN,25000.0,NaN,3526.0,NaN,NaN
2866,H77,Kremasta,437.2,NaN,HDAM,EL,38.890417,21.499583,160.0,4495.0,694000.0,848.0,2949.0,42794.0,NaN
2929,H842,Agras AGRAS - Agras Hydroelectric Power Plant ...,50.0,NaN,HROR,EL,40.806800,22.021500,NaN,NaN,NaN,NaN,2912.0,42788.0,NaN
3056,H98,Thisavros φράγμα θησαυρού,384.0,384.0,HPHS,EL,41.267032,24.500878,135.0,NaN,3820.0,NaN,2894.0,42801.0,NaN